### ISSUE TITLE
"Put into the battle zone" effects are broken

### ISSUE THREAD

**Issue by ghost** [sindreslungaard/shobu-issue-tracker#16]
Cards like "Bronze-Arm Tribe", "Stringer Worm" or "Rayla, Truth Enforcer" have effects when they are put into the battle zone. These effects can be triggered multiple times, when you try to play one of those cards with less mana than needed. The effect of the card will trigger but it will be still in your hand and you can repeat this process.

**Comment by sindreslungaard** [comment]
Card effects are no longer triggered when clicking "choose" with insufficient mana
